### ISSUE TITLE
glm classification error

### ISSUE THREAD

**Issue by tsailiming** [databricks/spark-perf#47]
On Spark 1.2.0
```
15/01/26 14:15:07 INFO scheduler.DAGScheduler: Job 0 finished: count at MLAlgorithmTests.scala:204, took 122.066741 s
Exception in thread "main" java.lang.IllegalArgumentException: GLMClassificationTest given incompatible (loss, regType) = (logistic, l2). Note the set of supp
orted combinations increases in later Spark versions.
        at mllib.perf.onepointtwo.GLMClassificationTest.runTest(MLAlgorithmTests.scala:238)
        at mllib.perf.onepointtwo.GLMClassificationTest.runTest(MLAlgorithmTests.scala:167)
        at mllib.perf.onepointtwo.RegressionAndClassificationTests.run(MLAlgorithmTests.scala:38)
        at mllib.perf.onepointtwo.TestRunner$$anonfun$2.apply(TestRunner.scala:55)
        at mllib.perf.onepointtwo.TestRunner$$anonfun$2.apply(TestRunner.scala:53)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.Range.foreach(Range.scala:141)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at mllib.perf.onepointtwo.TestRunner$.main(TestRunner.scala:53)
        at mllib.perf.onepointtwo.TestRunner.main(TestRunner.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by tsailiming** [comment]
I'm still getting this error in the latest spark-perf and Spark 1.2.1

**Comment by nchammas** [comment]
cc @mengxr

**Comment by mengxr** [comment]
Please ignore this test. We don't support `(logistic, l2)` yet, which I plan to add soon.
