### ISSUE TITLE
Error when running tests: java.lang.NoSuchMethodError: joptsimple.ArgumentAcceptingOptionSpec.required()

### ISSUE THREAD

**Issue by ravi9** [databricks/spark-perf#81]
I get the following error when running tests. Proper classpath is not being set. Any suggestions are appreciated.
```
Exception in thread "main" java.lang.NoSuchMethodError: joptsimple.ArgumentAcceptingOptionSpec.required()Ljoptsimple/ArgumentAcceptingOptionSpec;
	at mllib.perf.PerfTest$$anonfun$addOptionsToParser$1.apply(PerfTest.scala:80)
	at mllib.perf.PerfTest$$anonfun$addOptionsToParser$1.apply(PerfTest.scala:79)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
```
```
Exception in thread "main" java.lang.IllegalArgumentException: int is not a value type
	at joptsimple.internal.Reflection.findConverter(Reflection.java:66)
	at joptsimple.ArgumentAcceptingOptionSpec.ofType(ArgumentAcceptingOptionSpec.java:111)
	at mllib.perf.PerfTest$$anonfun$addOptionsToParser$3.apply(PerfTest.scala:86)
```

Thank you

**Comment by ravi9** [comment]
I resolved it by passing
